### ISSUE TITLE
is there csg implemented?

### ISSUE THREAD

**Issue by saravanan2020** [NoteCAD/NoteCAD#35]
Is it CSG implemented in your library?

**Comment by saravanan2020** [comment]
to use this library where to start?. is there any demo in your NoteCAD?

**Comment by Evil-Spirit** [comment]
NoteCAD use CSG for combining each group of extrusion. You can just go to http://notecad.xyz, load two simple STL models and move them to get combined mesh (you can export this as STL). 
Sample code you can see here https://github.com/NoteCAD/NoteCAD/blob/master/Assets/Code/DetailEditor/DetailEditor.cs#L201. But this is not my library.

**Comment by saravanan2020** [comment]
In that CSG library, solids made from polygons, Is it polygons are triangles only?  Each polygon contains three vertices only? or polygons made of quad (4 vertices). or random vertices?. How can i store solid into mesh and vice-versa at runtime? 
Thanks.

**Comment by Evil-Spirit** [comment]
I don't actually know how this work inside, I just give triangles to this library and get back triangles.

**Comment by saravanan2020** [comment]
through that detaileditor.cs?

**Comment by Evil-Spirit** [comment]
to convert triangle mesh to Solid
https://github.com/NoteCAD/NoteCAD/blob/6ab6ce298515ab15331fd39210aa1f8f24d2faad/Assets/Code/Geometry/MeshUtils.cs#L187
and back
https://github.com/NoteCAD/NoteCAD/blob/6ab6ce298515ab15331fd39210aa1f8f24d2faad/Assets/Code/Geometry/MeshUtils.cs#L316

**Comment by saravanan2020** [comment]
Thanks. I will try that.
