### ISSUE TITLE
Solver

### ISSUE THREAD

**Issue by Evil-Spirit** [NoteCAD/NoteCAD#40]

**Comment by Evil-Spirit** [comment]
@tenacious here is the Solver for C#

**Comment by Evil-Spirit** [comment]
@tenacious Please, specify what brower did you use?

**Comment by tenacious** [comment]
win10 , nvidia card.

Just for curiosity i tried on another pc. Now i can draw circles and other
entities but if i click and drag somewhere, all the viewport it's dragged.
See
https://www.screencast.com/t/h1PmwyRZ6

Also seem the viewport don't scale to viewable area but has fixed dimension.

I'm not planning to use this or any components, so i'm not able to give you
deeper feedback. Good luck with the project.


Il giorno gio 8 nov 2018 alle ore 09:26 Alexey Egorov <
notifications@github.com> ha scritto:

**Comment by Evil-Spirit** [comment]
@tenacious thank you! You have provided enough information for me! Good luck!
