### ISSUE TITLE
Line + Arc + ParallelTool not working

### ISSUE THREAD

**Issue by foror** [NoteCAD/NoteCAD#47]
Draw line, connect it with arc and apply ParallelTool. Expected line parallel to first segment of arc line, but nothing happens.

**Comment by Evil-Spirit** [comment]
Did you mean it should be Tangent?

**Comment by foror** [comment]
![arc-parallel-line](https://user-images.githubusercontent.com/95097/49982705-3c790780-ff88-11e8-8107-3ecec818ee03.png)

**Comment by Evil-Spirit** [comment]
To get the same result you should apply Tangent constraint. Tangent is not Parallel literally, Tangent is  Parallel + PointOn. I can do Parallel for Entities, but I can't imagine how often this can be useful.

**Comment by Evil-Spirit** [comment]
I just can bind some tangent to parallel, but not sure if it right or it wrong.

**Comment by Evil-Spirit** [comment]
Yes, you are right, there a lot of documentations should be written.... For ex. you can select Dim, do distance between circles/arc with connected centers and you will get the interesting result ) Also, you can select Dim and select circle center and then circle itself and you will get the interesting result )

**Comment by Evil-Spirit** [comment]
answered
