### ISSUE TITLE
Not working Horizontal constraint between lines on arc

### ISSUE THREAD

**Issue by foror** [NoteCAD/NoteCAD#49]
[horizontal.xml.zip](https://github.com/NoteCAD/NoteCAD/files/2679040/horizontal.xml.zip)

![horizontal](https://user-images.githubusercontent.com/95097/49989935-08144400-ffa6-11e8-94ae-f77ac15e5b68.png)

**Comment by Evil-Spirit** [comment]
Probably, you cicked ctrl+z and radius constraint turns into diameter because showasradius is not saved (bug). I will fix is soon. Thank you!
