### ISSUE TITLE
Clipperlib offset problem

### ISSUE THREAD

**Issue by saravanan2020** [NoteCAD/NoteCAD#52]
Are you using clipperlib?. I am trying clipperlib offset with 2d shapes. but it works good only for rectangles. for circles its smoothing the points and offsetting gives me irregular shape of original circle. Any suggestions please?
Thanks.

Note: i tried all the possibilities of options available with clipperlib offset function.

**Comment by Evil-Spirit** [comment]
No, I don't use this library and have no offset functions right now. For what purpose you are going you use offsets?

**Comment by Evil-Spirit** [comment]
[Hope this will help](http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Types/JoinType.htm)

**Comment by saravanan2020** [comment]
> No, I don't use this library and have no offset functions right now. For what purpose you are going you use offsets?

For 2D CAD drawings

**Comment by saravanan2020** [comment]
It came correct. Clipper using different proportions (scale) than unity3d. so for clipper calculations we have to use some big number (multiply with some big number for clipper calculations, and divide with same number for unity3d). Anyway, thank you.

**Comment by saravanan2020** [comment]
Also you can use clipperlib for 2d polygon boolean operations.

**Comment by Evil-Spirit** [comment]
Will use it definitely! Thanks
