### ISSUE TITLE
Which version of unity does this project support?Why I use unity2018.3.6 to open the assembly will be missing

### ISSUE THREAD

**Issue by 13704017891** [NoteCAD/NoteCAD#53]

**Comment by andybak** [comment]
https://github.com/NoteCAD/NoteCAD/blob/master/ProjectSettings/ProjectVersion.txt

**Comment by Evil-Spirit** [comment]
Hi! Sorry for delayed response.
Probably you haven't updated submodules.

**Comment by Evil-Spirit** [comment]
probably should be sucessfully build using new fresh version of the unity3d
